<?php
/** @var  Magento\Catalog\Model\Product $product */
$product = $block->getSaleableItem();
$children = $product->getTypeInstance()
                    ->getUsedProducts($product);

$pricingRenderer = null;
try {
    $pricingRenderer = \Magento\Framework\App\ObjectManager::getInstance()
                                                           ->get('Magento\Framework\Pricing\Render');
} catch (Throwable $ex) {
    echo $ex->getMessage();
}
if (!is_null($pricingRenderer)) {
    foreach ($children as $childProduct) {
        ?>
        <div class="child_price child_price_<?php echo $childProduct->getId(); ?>">
            <?php

            /** @var Magento\Framework\Pricing\Render $pricingRenderer */
            $arguments = [
                'zone' => \Magento\Framework\Pricing\Render::ZONE_ITEM_VIEW,
            ];
            echo $pricingRenderer->render('final_price', $childProduct, $arguments);
            ?>
        </div>
        <?php
    }
}
