<?php
declare(strict_types=1);

use Attlaz\Base\Block\System\Config\Form\Branding;

/** @var $block Branding */
/** @var $escaper \Magento\Framework\Escaper */
?>
<div class="attlaz-branding">
    <div class="logo-wrap">
        <img width="120" src="<?= $escaper->escapeHtmlAttr($block->getLogo()) ?>"/>
    </div>

    <div class="content">
        <p>
            <span class="title">
                <?= $escaper->escapeHtml(__('Attlaz - Create the data network of your organization')); ?>
            </span>
            <br/>
            Visit the <a href="<?= $escaper->escapeHtmlAttr($block->getWebsiteUrl()) ?>" target="_blank">
                Attlaz website
            </a> <?= $escaper->escapeHtml(__('for support and more information,')) ?><br/>
            <?= $escaper->escapeHtml(__('or go to the')) ?>
            <a href="<?= $escaper->escapeHtmlAttr($block->getAppUrl()) ?>" target="_blank">
                app
            </a> to manage your project</p>
    </div>
</div>
